services:
  db:
    image: mysql:8.0
    container_name: gilded_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gilded_restaurant
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gilded_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: adminpass
